export const categoriesSeed = [
  { id: 'cat-frp', slug: 'frp', name: 'FRP (Desbloqueio de Conta)', icon: 'shield', color: '#00ff66' },
  { id: 'cat-imei', slug: 'imei', name: 'Reparo de IMEI', icon: 'chip', color: '#22d3ee' },
  { id: 'cat-ativacoes', slug: 'ativacoes', name: 'Ativações', icon: 'bolt', color: '#facc15' },
  { id: 'cat-mdm', slug: 'mdm', name: 'MDM / Gerenciamento', icon: 'lock', color: '#f472b6' },
  { id: 'cat-unlock', slug: 'unlock', name: 'Desbloqueio de Operadora', icon: 'unlock', color: '#a78bfa' },
  { id: 'cat-desbloqueios', slug: 'desbloqueios', name: 'Outros Desbloqueios', icon: 'wrench', color: '#fb923c' },
];

export const servicesSeed = [
  { id: 'srv-1', categoryId: 'cat-frp', slug: 'samsung-frp-remocao-de-conta-google', name: 'Samsung FRP (Remoção de Conta Google)', description: 'Remoção de conta Google via servidor. Suporta modelos 2016+ (A, S, Note, M).', price: 12.9, deliveryTime: 'Instantâneo' },
  { id: 'srv-2', categoryId: 'cat-frp', slug: 'xiaomi-frp-mi-cloud', name: 'Xiaomi FRP / MI Cloud', description: 'Remoção de conta MI e Mi Cloud para Redmi, POCO e Xiaomi.', price: 9.9, deliveryTime: 'Instantâneo' },
  { id: 'srv-3', categoryId: 'cat-frp', slug: 'motorola-frp', name: 'Motorola FRP', description: 'Remoção de FRP para Motorola sem necessidade de flashear.', price: 14.9, deliveryTime: 'Instantâneo' },
  { id: 'srv-4', categoryId: 'cat-frp', slug: 'lg-frp', name: 'LG FRP', description: 'Remoção de conta Google para aparelhos LG.', price: 11.9, deliveryTime: 'Até 5 min' },
  { id: 'srv-5', categoryId: 'cat-frp', slug: 'apple-frp-icloud-remocao', name: 'Apple FRP (iCloud - Remoção)', description: 'Remoção de iCloud vinculado. Suporta iPhone e iPad.', price: 59.9, deliveryTime: 'Até 24h' },
  { id: 'srv-6', categoryId: 'cat-imei', slug: 'reparo-de-imei-samsung', name: 'Reparo de IMEI Samsung', description: 'Correção de IMEI em aparelhos Samsung (certificado).', price: 25, deliveryTime: 'Até 30 min' },
  { id: 'srv-7', categoryId: 'cat-imei', slug: 'reparo-de-imei-xiaomi', name: 'Reparo de IMEI Xiaomi', description: 'Correção de IMEI para Xiaomi, Redmi e POCO.', price: 25, deliveryTime: 'Até 30 min' },
  { id: 'srv-8', categoryId: 'cat-imei', slug: 'alteracao-de-imei-motorola', name: 'Alteração de IMEI Motorola', description: 'Alteração de IMEI para aparelhos Motorola com bootloader liberado.', price: 30, deliveryTime: 'Até 1h' },
  { id: 'srv-9', categoryId: 'cat-ativacoes', slug: 'ativacao-ios-qualquer-versao', name: 'Ativação iOS (Qualquer versão)', description: 'Ativação do aparelho sem Apple ID, qualquer versão do iOS.', price: 35, deliveryTime: 'Até 2h' },
  { id: 'srv-10', categoryId: 'cat-mdm', slug: 'remocao-mdm-iphone', name: 'Remoção MDM iPhone', description: 'Remoção de gerenciamento corporativo (MDM) para iPhones.', price: 49.9, deliveryTime: 'Até 24h' },
  { id: 'srv-11', categoryId: 'cat-mdm', slug: 'remocao-mdm-android-zero-touch-dpc', name: 'Remoção MDM Android (Zero Touch / DPC)', description: 'Remoção de inscrição em enterprise mobility para Android.', price: 22.9, deliveryTime: 'Até 1h' },
  { id: 'srv-12', categoryId: 'cat-unlock', slug: 'desbloqueio-de-operadora-simlock-iphone', name: 'Desbloqueio de Operadora (Simlock) iPhone', description: 'Desbloqueio permanente de operadora via base de dados oficial.', price: 39.9, deliveryTime: 'Instantâneo' },
  { id: 'srv-13', categoryId: 'cat-unlock', slug: 'desbloqueio-de-operadora-simlock-samsung', name: 'Desbloqueio de Operadora (Simlock) Samsung', description: 'Desbloqueio de simlock para aparelhos Samsung.', price: 29.9, deliveryTime: 'Até 30 min' },
  { id: 'srv-14', categoryId: 'cat-desbloqueios', slug: 'desbloqueio-de-conta-google-tela-bloqueada', name: 'Desbloqueio de Conta Google (Tela bloqueada)', description: 'Remoção de conta Google da tela de bloqueio (lock screen), sem perder dados.', price: 15.9, deliveryTime: 'Até 15 min' },
  { id: 'srv-15', categoryId: 'cat-desbloqueios', slug: 'desbloqueio-de-padrao-pin', name: 'Desbloqueio de Padrão / PIN', description: 'Remoção de padrão, PIN ou senha de bloqueio em Android.', price: 18.9, deliveryTime: 'Até 15 min' },
  { id: 'srv-16', categoryId: 'cat-desbloqueios', slug: 'remocao-de-frp-via-emergency-account', name: 'Remoção de FRP via EMERGENCY ACCOUNT', description: 'Remoção de conta Google via conta emergencial para modelos selecionados.', price: 8.9, deliveryTime: 'Instantâneo' },
];

export const marcas = ['Samsung', 'Xiaomi', 'Motorola', 'Apple', 'LG', 'POCO', 'Redmi', 'Asus', 'Nokia', 'Realme', 'Huawei', 'Oppo'];
export const pagamentos = ['PIX', 'Cartão', 'Cripto', 'Boleto'];

export const remoteServicesSeed = [
  { id: 'remote-1', name: 'Motorola Moto FRP Unlock Fastboot Mode Instant MTK Only', price: 8.9, deliveryTime: 'Minutes' },
  { id: 'remote-2', name: 'Xiaomi FRP REMOVE INSTANT BY USB ASSISTANT MODE', price: 4.4, deliveryTime: 'Miniutes' },
  { id: 'remote-3', name: 'AMT Android Multi Tool RENT (2H) Instant S2', price: 0.39, deliveryTime: 'Instant' },
  { id: 'remote-4', name: 'AMT Android Multi Tool RENT 2H Instant', price: 0.49, deliveryTime: 'Instant' },
  { id: 'remote-5', name: 'Dft Pro Tool Rent 48 hours Instant', price: 1.99, deliveryTime: 'Instant' },
  { id: 'remote-6', name: 'EFT Pro Tool 6 Hour Rent instant', price: 3, deliveryTime: 'Minutes' },
  { id: 'remote-7', name: 'TSM Tool Pro Rent 3 hours Instant', price: 0.94, deliveryTime: 'Instant' },
  { id: 'remote-8', name: 'Unlock Tool RENT (6H) Instant S2 (Limited 70 Account)', price: 0.54, deliveryTime: 'Instant' },
  { id: 'remote-9', name: 'Unlock Tool Rent Instant 6 Hour', price: 0.51, deliveryTime: 'Instant' },
  { id: 'remote-10', name: 'Z3X SamsTool Online Rent 1Month (Pre Login)', price: 25, deliveryTime: '1-30 Miniutes' },
  { id: 'remote-11', name: 'Rent Service Problem Submit', price: 0, deliveryTime: '1-10 Miniutes' },
  { id: 'remote-12', name: 'AndroidWinTool (AWT) Rent [48 Hours]', price: 2.1, deliveryTime: 'Instant' },
  { id: 'remote-13', name: 'AnonySHU Rent [12 Hours]', price: 3, deliveryTime: 'Instant' },
  { id: 'remote-14', name: 'Griffin-Unlocker-Tool (Premium Account) Tool RENT [6 Hours]', price: 3, deliveryTime: 'Instant' },
  { id: 'remote-15', name: '(Filewale.com) Firmware Request', price: 1.1, deliveryTime: 'Miniutes' },
  { id: 'remote-16', name: '(givemerom.com) (1MB to 1GB) GiveMeROM Firmware Request', price: 0.9, deliveryTime: '1 hour' },
  { id: 'remote-17', name: '(hello-firmware.com) Firmware Request Here', price: 1.8, deliveryTime: '10-30 Miniutes' },
  { id: 'remote-18', name: '(Support.halabtech.com) 13GB to 30GB Halabtech Firmware Request', price: 4.5, deliveryTime: '3-6 Hour' },
  { id: 'remote-19', name: '(Support.halabtech.com) 1MB to 1GB Halabtech Firmware Request', price: 0.9, deliveryTime: '1-30 Minute' },
  { id: 'remote-20', name: '(Support.halabtech.com) 2GB to 3GB Halabtech Firmware Request', price: 1.4, deliveryTime: '1-3 Hour' },
  { id: 'remote-21', name: '(Support.halabtech.com) 3GB to 4GB Halabtech Firmware Request', price: 2, deliveryTime: '1-3 Hour' },
  { id: 'remote-22', name: '(Support.halabtech.com) 5GB to 9GB Halabtech Firmware Request', price: 2.5, deliveryTime: '3-6 Hour' },
  { id: 'remote-23', name: '(Support.halabtech.com) 9GB to13GB Halabtech Firmware Request', price: 2.9, deliveryTime: '3-6 Hour' },
  { id: 'remote-24', name: 'APIZU MDM TOOL PRO Rent (Time: 4 Hours)', price: 2, deliveryTime: 'Miniutes' },
  { id: 'remote-25', name: 'CellTool/SamsungTool.us Samsung Tool Rent 12 Hours', price: 2.9, deliveryTime: 'Instant' },
  { id: 'remote-26', name: 'CF Tools Rent Instant [6 Hours]', price: 0.78, deliveryTime: 'Instant' },
  { id: 'remote-27', name: 'CHEETAH TOOL RENT [25 Days] instant', price: 9, deliveryTime: 'Instant' },
  { id: 'remote-28', name: 'CM2 Dongle Rent (New Version) [1 Hour]', price: 2.3, deliveryTime: '1-10 Minutes' },
  { id: 'remote-29', name: 'CM2 Dongle Rent (New Version) [1 Hour] Premium', price: 2.8, deliveryTime: '1-10 Minutes' },
  { id: 'remote-30', name: 'Dft Pro Tool Rent [45 hours] Instant S2', price: 2.1, deliveryTime: 'Instant' },
  { id: 'remote-31', name: 'File Password Only (HALABTECH)', price: 0.3, deliveryTime: '1-30 Minute' },
  { id: 'remote-32', name: 'GivemeROM File Request (13GB to 30GB) Firmware Request', price: 4, deliveryTime: '3-6 Hour' },
  { id: 'remote-33', name: 'GivemeROM File Request (2GB to 3GB) Firmware Request', price: 1.4, deliveryTime: '1-3 Hour' },
  { id: 'remote-34', name: 'GivemeROM File Request (5GB to 9GB) Firmware Request', price: 2.5, deliveryTime: '3-6 hour' },
  { id: 'remote-35', name: 'GivemeROM File Request (9GB to 13GB) Firmware Request', price: 2.4, deliveryTime: '3-6 Hour' },
  { id: 'remote-36', name: 'GivemeROM File Request 3GB to 4GB Firmware Request', price: 2, deliveryTime: '1-3 Hour' },
  { id: 'remote-37', name: 'Griffin-Unlocker Tool RENT instant [6 Hours]', price: 1.8, deliveryTime: 'Instant' },
  { id: 'remote-38', name: 'HSPro Tool Access Rent For 6 Hours (Temporarily Login - No Refundable)', price: 3.5, deliveryTime: 'Miniutes' },
  { id: 'remote-39', name: 'Kg Killer Tool Rent [4 Hours] Instant', price: 0.99, deliveryTime: 'Instant' },
  { id: 'remote-40', name: 'MDM Fix Tool Rent 6 Hour Instant', price: 1.69, deliveryTime: 'Instant' },
  { id: 'remote-41', name: 'Mst [MobileSea Sevice Tool] Instant [6 hours]', price: 0.49, deliveryTime: 'Instant' },
  { id: 'remote-42', name: 'MultiUnlock Tool Access Rent For 12 Hours (Login By AnyDesk)', price: 2, deliveryTime: 'Instant' },
  { id: 'remote-43', name: 'Octoplus Box - FRP Tool Rent (1 Hour)', price: 2.3, deliveryTime: '1-10 Minutes' },
  { id: 'remote-44', name: 'Octoplus Box - Huawei Tool Rent (1 Hour)', price: 2.5, deliveryTime: '1-10 Miniutes' },
  { id: 'remote-45', name: 'Octoplus Box - LG Tool Rent (1 Hour)', price: 2.3, deliveryTime: '1-10 Minutes' },
  { id: 'remote-46', name: 'Octoplus Box - Samsung Tool (Exynos Cup) Rent (1 Hour)', price: 2.3, deliveryTime: '1-10 Minutes' },
  { id: 'remote-47', name: 'Pandora Tool { Digital } Login (Rent 48 Hours)', price: 10, deliveryTime: '1-30 Miniutes' },
  { id: 'remote-48', name: 'Pandora Tool { Digital } Login Rent 1 month', price: 20, deliveryTime: 'Miniutes' },
  { id: 'remote-49', name: 'Pandora Tool { Digital } Login Rent 2 months 60 days', price: 28, deliveryTime: 'Miniutes' },
  { id: 'remote-50', name: 'Relogin Your, OCTOPLUS, SIGMA Within 1 Hour After Ordering', price: 0, deliveryTime: '1-10 Min' },
  { id: 'remote-51', name: 'RTC Tool Rent 6 Hour Instant', price: 2, deliveryTime: 'Instant' },
  { id: 'remote-52', name: 'SIGMA PLUS 1 Hour Rent', price: 3.2, deliveryTime: '1-10 Minutes' },
  { id: 'remote-53', name: 'Sigma Plus Rent [1 Hours]', price: 2, deliveryTime: '1-10 Minutes' },
  { id: 'remote-54', name: 'Tfm Tool Rent [3 hours] Instant', price: 0.69, deliveryTime: 'Instant' },
  { id: 'remote-55', name: 'TR Tools Pro Rent Instant 24 Hour', price: 3.3, deliveryTime: 'Instant' },
  { id: 'remote-56', name: 'UnlockTool Rent (Login + Password) 12 Hours', price: 0.89, deliveryTime: 'Instant' },
  { id: 'remote-57', name: 'UnlockTool Rent (Login + Password) 24 Hours', price: 1.19, deliveryTime: 'Instant' },
  { id: 'remote-58', name: 'Z3X Samsung Tool Pro Rent (Box) 1 Hours', price: 2.5, deliveryTime: '1-30 Miniutes' },
  { id: 'remote-59', name: 'SmartTool Pro Access Rent For 10 Hours (Direct Source)', price: 3, deliveryTime: 'Instant' },
];